"""BSE-first session runner.

This module owns the market clock loop, quote/cancel flow, participant activity,
and per-run artifact row generation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from lob_market_making_agents.agents import create_mm_trader
from lob_market_making_agents.env.bse_loader import load_bse_module
from lob_market_making_agents.env.models import PopulationConfig, RegimeConfig, SessionConfig
from lob_market_making_agents.env.population import PopulationBundle, build_external_order, build_population


BSE = load_bse_module()


@dataclass(frozen=True)
class SessionResult:
    """BSE-native run artifacts generated by one session."""

    tape_rows: tuple[dict[str, Any], ...]
    lob_frames: tuple[dict[str, Any], ...]
    mm_state_rows: tuple[dict[str, Any], ...]
    competitor_state_rows: tuple[dict[str, Any], ...]
    summary: dict[str, float]


def run_bse_session(
    *,
    seed: int,
    agent_name: str,
    agent_params: dict[str, Any],
    regime: RegimeConfig,
    session_config: SessionConfig,
    population_config: PopulationConfig,
    agent_settings: dict[str, Any] | None = None,
) -> SessionResult:
    """Run one full BSE session and return normalized artifact rows."""
    rng = np.random.default_rng(seed)
    exchange = BSE.Exchange()

    agent_cfg = dict(agent_settings or {})
    competitor_agent = str(agent_cfg.get("competitor_agent", "A"))
    competitor_params = dict(agent_cfg.get("competitor_params", {"spread": 2.0}))

    main_mm = create_mm_trader(
        agent_name=agent_name,
        tid=population_config.mm_trader_id,
        params=agent_params,
        time=0.0,
    )
    population = build_population(
        regime=regime,
        population_config=population_config,
        competitor_agent=competitor_agent,
        competitor_params=competitor_params,
    )

    mm_traders: dict[str, Any] = {main_mm.tid: main_mm}
    for competitor in population.competitor_mms:
        mm_traders[competitor.tid] = competitor

    reference_mid = float(session_config.base_midprice)
    mid_history: list[float] = [reference_mid]

    tape_rows: list[dict[str, Any]] = []
    lob_frames: list[dict[str, Any]] = []
    mm_state_rows: list[dict[str, Any]] = []
    competitor_state_rows: list[dict[str, Any]] = []

    # Rolling window of external order-flow signs (+1 buy, -1 sell) for flow imbalance feature.
    # Only external participant-initiated trades are counted — MM quote activity is excluded.
    recent_trade_signs: list[float] = []
    flow_window = max(1, int(session_config.vol_window))

    tape_cursor = 0
    volatility_sigma = _volatility_sigma(regime.volatility)

    for step in range(1, int(session_config.episode_steps) + 1):
        timestamp = int(step)
        time = float(step)

        reference_mid += float(rng.normal(0.0, volatility_sigma))

        step_fill_side = "none"
        step_fill_price: float | None = None
        step_fill_qty = 0.0
        # informed is derived from the participant actually drawn this step,
        # not an independent probability draw — see external participant block below.
        informed = False

        def apply_trade(trade: dict[str, Any] | None, incoming_order: Any | None) -> None:
            nonlocal step_fill_side, step_fill_price, step_fill_qty
            if trade is None or incoming_order is None:
                return

            fills = _map_trade_to_mm_fills(trade=trade, incoming_order=incoming_order, mm_tids=set(mm_traders.keys()))
            if not fills:
                return

            fill_price = float(trade["price"])
            fill_qty = float(trade.get("qty", 1.0))
            for mm_tid, fill_side in fills.items():
                mm_traders[mm_tid].on_fill(fill_side=fill_side, fill_price=fill_price, fill_qty=fill_qty)
                if mm_tid == main_mm.tid and step_fill_side == "none":
                    step_fill_side = fill_side
                    step_fill_price = fill_price
                    step_fill_qty = fill_qty

        _process_mm_quotes(
            exchange=exchange,
            mm_traders=tuple(mm_traders.values()),
            time=time,
            reference_mid=reference_mid,
            vol_proxy=_rolling_volatility(mid_history, int(session_config.vol_window)),
            on_trade=apply_trade,
        )

        if (
            population.external_participants
            and rng.random() < float(session_config.external_order_probability)
        ):
            participant = population.external_participants[
                int(rng.integers(0, len(population.external_participants)))
            ]
            # Derive informed directly from participant kind: a step is adversely informed
            # if and only if the participant drawn is a toxic trader.
            informed = participant.kind == "toxic"

            lob_public = exchange.publish_lob(time, None, False)
            external_order, _ = build_external_order(
                participant=participant,
                time=time,
                qid=int(lob_public["QID"]),
                lob=lob_public,
                reference_mid=reference_mid,
                rng=rng,
            )
            if external_order is not None:
                trade = exchange.process_order(time, external_order, None, False)
                apply_trade(trade, external_order)
                # Track external order-flow sign for Agent C's flow imbalance feature.
                # Only external participant-initiated trades count (not MM quote activity).
                if trade is not None:
                    sign = 1.0 if str(external_order.otype) == "Bid" else -1.0
                    recent_trade_signs.append(sign)
                    if len(recent_trade_signs) > flow_window:
                        recent_trade_signs.pop(0)

        if informed:
            adverse = max(1.0, volatility_sigma * 2.0)
            if step_fill_side == "bid":
                reference_mid -= adverse
            elif step_fill_side == "ask":
                reference_mid += adverse

        lob_public = exchange.publish_lob(time, None, False)
        best_bid = lob_public["bids"]["best"]
        best_ask = lob_public["asks"]["best"]
        midprice = _mid_from_lob(lob_public, reference_mid)
        reference_mid = float(midprice)
        mid_history.append(reference_mid)

        # Flow imbalance: mean signed direction of recent external trades.
        # +1.0 = all buys, -1.0 = all sells, 0.0 = balanced or no history yet.
        flow_imbalance = (
            sum(recent_trade_signs) / len(recent_trade_signs)
            if recent_trade_signs else 0.0
        )

        while tape_cursor < len(exchange.tape):
            tape_rows.append(_normalize_tape_item(tape_cursor, exchange.tape[tape_cursor]))
            tape_cursor += 1

        main_bid = getattr(main_mm.last_bid_order, "price", None)
        main_ask = getattr(main_mm.last_ask_order, "price", None)
        pnl = main_mm.pnl(midprice)

        lob_frames.append(
            {
                "timestamp": timestamp,
                "best_bid": float(best_bid) if best_bid is not None else "",
                "best_ask": float(best_ask) if best_ask is not None else "",
                "midprice": float(midprice),
                "bid_depth": float(lob_public["bids"]["n"]),
                "ask_depth": float(lob_public["asks"]["n"]),
            }
        )
        mm_state_rows.append(
            {
                "timestamp": timestamp,
                "inventory": float(main_mm.inventory),
                "cash": float(main_mm.cash),
                "pnl": float(pnl),
                "bid_quote": float(main_bid) if main_bid is not None else "",
                "ask_quote": float(main_ask) if main_ask is not None else "",
                "fill_side": step_fill_side,
                "fill_price": float(step_fill_price) if step_fill_price is not None else "",
                "fill_qty": float(step_fill_qty),
                "informed": int(informed),
                "flow_imbalance": float(flow_imbalance),
            }
        )

        for competitor in population.competitor_mms:
            comp_bid = getattr(competitor.last_bid_order, "price", None)
            comp_ask = getattr(competitor.last_ask_order, "price", None)
            competitor_state_rows.append(
                {
                    "timestamp": timestamp,
                    "trader_id": competitor.tid,
                    "inventory": float(competitor.inventory),
                    "cash": float(competitor.cash),
                    "pnl": float(competitor.pnl(midprice)),
                    "bid_quote": float(comp_bid) if comp_bid is not None else "",
                    "ask_quote": float(comp_ask) if comp_ask is not None else "",
                }
            )

    summary = _build_summary(mm_state_rows=mm_state_rows, lob_frames=lob_frames)
    return SessionResult(
        tape_rows=tuple(tape_rows),
        lob_frames=tuple(lob_frames),
        mm_state_rows=tuple(mm_state_rows),
        competitor_state_rows=tuple(competitor_state_rows),
        summary=summary,
    )


def _process_mm_quotes(
    *,
    exchange: Any,
    mm_traders: tuple[Any, ...],
    time: float,
    reference_mid: float,
    vol_proxy: float,
    on_trade: Any,
) -> None:
    for mm in mm_traders:
        _cancel_if_present(exchange=exchange, time=time, order=getattr(mm, "last_bid_order", None))
        _cancel_if_present(exchange=exchange, time=time, order=getattr(mm, "last_ask_order", None))

        lob_public = exchange.publish_lob(time, None, False)
        mid = _mid_from_lob(lob_public, reference_mid)
        bid_order, ask_order = mm.make_quotes(
            time=time,
            qid=int(lob_public["QID"]),
            midprice=mid,
            volatility_proxy=vol_proxy,
        )

        bid_trade = exchange.process_order(time, bid_order, None, False)
        on_trade(bid_trade, bid_order)

        ask_trade = exchange.process_order(time, ask_order, None, False)
        on_trade(ask_trade, ask_order)


def _cancel_if_present(*, exchange: Any, time: float, order: Any | None) -> None:
    if order is None:
        return
    exchange.del_order(time, order, None, False)


def _map_trade_to_mm_fills(
    *, trade: dict[str, Any], incoming_order: Any, mm_tids: set[str]
) -> dict[str, str]:
    """Map a BSE trade into MM fill sides for participating MM trader IDs."""
    fills: dict[str, str] = {}
    incoming_tid = str(incoming_order.tid)
    incoming_side = str(incoming_order.otype)

    if incoming_tid in mm_tids:
        fills[incoming_tid] = "bid" if incoming_side == "Bid" else "ask"

    passive_tid = str(trade.get("party1", ""))
    if passive_tid in mm_tids and passive_tid != incoming_tid:
        fills[passive_tid] = "ask" if incoming_side == "Bid" else "bid"

    return fills


def _normalize_tape_item(sequence: int, item: dict[str, Any]) -> dict[str, Any]:
    event_type = str(item.get("type", "Unknown"))
    row = {
        "sequence": int(sequence),
        "timestamp": float(item.get("time", 0.0)),
        "event_type": event_type,
        "price": "",
        "qty": "",
        "party1": "",
        "party2": "",
        "tid": "",
        "side": "",
        "qid": "",
    }

    if event_type == "Trade":
        row["price"] = float(item.get("price", 0.0))
        row["qty"] = float(item.get("qty", 0.0))
        row["party1"] = str(item.get("party1", ""))
        row["party2"] = str(item.get("party2", ""))
    elif event_type == "Cancel":
        order = item.get("order")
        if order is not None:
            row["price"] = float(getattr(order, "price", 0.0))
            row["tid"] = str(getattr(order, "tid", ""))
            row["side"] = str(getattr(order, "otype", ""))
            row["qid"] = int(getattr(order, "qid", 0))

    return row


def _mid_from_lob(lob: dict[str, Any], fallback_mid: float) -> float:
    best_bid = lob["bids"]["best"]
    best_ask = lob["asks"]["best"]
    if best_bid is not None and best_ask is not None:
        return (float(best_bid) + float(best_ask)) / 2.0
    return float(fallback_mid)


def _rolling_volatility(mid_history: list[float], window: int) -> float:
    if window <= 1 or len(mid_history) < 3:
        return 0.0
    tail = np.asarray(mid_history[-window:], dtype=float)
    if tail.size < 3:
        return 0.0
    returns = np.diff(tail)
    return float(np.std(returns))


def _volatility_sigma(level: str) -> float:
    key = str(level).strip().lower()
    if key == "low":
        return 0.25
    if key == "medium":
        return 0.6
    if key == "high":
        return 1.2
    return 0.5


def _build_summary(mm_state_rows: list[dict[str, Any]], lob_frames: list[dict[str, Any]]) -> dict[str, float]:
    if not mm_state_rows:
        return {
            "steps": 0.0,
            "fills": 0.0,
            "final_midprice": 0.0,
            "final_inventory": 0.0,
            "final_cash": 0.0,
            "final_pnl": 0.0,
        }

    final_state = mm_state_rows[-1]
    final_lob = lob_frames[-1] if lob_frames else {"midprice": 0.0}
    fills = sum(1.0 for row in mm_state_rows if str(row.get("fill_side", "none")) != "none")

    return {
        "steps": float(len(mm_state_rows)),
        "fills": float(fills),
        "final_midprice": float(final_lob.get("midprice", 0.0)),
        "final_inventory": float(final_state.get("inventory", 0.0)),
        "final_cash": float(final_state.get("cash", 0.0)),
        "final_pnl": float(final_state.get("pnl", 0.0)),
    }
